version: "3"
services:
  api:
    image: $API_NODE_IMAGE
    labels:
      # enable traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      # setup service
      - traefik.http.services.service:${COMPOSE_PROJECT_NAME}:api.loadbalancer.server.port=3000
      # setup router
      - traefik.http.routers.router:${COMPOSE_PROJECT_NAME}:api.entrypoints=http
      - traefik.http.routers.router:${COMPOSE_PROJECT_NAME}:api.rule=Host(`${API_HOST}`)
      - traefik.http.routers.router:${COMPOSE_PROJECT_NAME}:api.service=service:${COMPOSE_PROJECT_NAME}:api
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${API_HOST}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    working_dir: /app
    command: ['apt-get update', 'apt-get install chromium', 'yarn start:dev']
    volumes:
      - $ROOT_DIR/services/api:/app
      #ignore this (performance issue)
      - /app/dist
    networks:
      - api
      - database
      - traefik
networks:
  api:
  traefik:
    external: true
