image: alpine

stages:
  - triggers

api:
  stage: triggers
  rules:
    - if: '$CI_COMMIT_TAG =~ /^api-.+/'
    - if: '$CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"'
      changes: 
          - services/api/**/*
    - when: never
  trigger:
      include: services/api/.gitlab-ci.yml

cms:
  stage: triggers
  rules:
    - if: '$CI_COMMIT_TAG =~ /^cms-.+/'
    - if: '$CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"'
      changes: 
          - services/cms/**/*
    - when: never
  trigger:
      include: services/cms/.gitlab-ci.yml

elastic-miner:
  stage: triggers
  rules:
    - if: '$CI_COMMIT_TAG =~ /^elastic-miner-.+/'
    - if: '$CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"'
      changes: 
          - services/elastic-miner/**/*
    - when: never
  trigger:
      include: services/elastic-miner/.gitlab-ci.yml

web:
  stage: triggers
  rules:
    - if: '$CI_COMMIT_TAG =~ /^web-.+/'
    - if: '$CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != "merge_request_event"'
      changes: 
          - services/web/**/*
    - when: never
  trigger:
      include: services/web/.gitlab-ci.yml
