version: "3"
services:
  database:
    image: mariadb:10.2
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
    networks:
      - database
    volumes:
      - $ROOT_DIR/services/database/dev-ops/docker/volumes/data:/var/lib/mysql
networks:
  database:
